### ISSUE TITLE
Quake 3

### ISSUE THREAD

**Issue by lollo78** [libretro/tyrquake#15]
Hi guys, it's possible to port Quake 3 in libretro?
https://www.raspberrypi.org/forums/viewt...=66&t=6473 (https://www.raspbian.org/RaspbianQuake3)
https://www.raspberrypi.org/blog/quake-i...-a-winner/
https://www.youtube.com/watch?v=tfbBDARr9aI

**Comment by leilei-** [comment]
Yes. It's more feasible than Quake2 since gamecode is compiled in QVMs so mods would work cross platform on it. The whole issue is does someone have time to do it, and can someone put TinyGL into it :)

I had plans for [this tree](https://github.com/OpenArena/engine) to go libretro but never got around to it.

**Comment by twinaphex** [comment]
I recently received an e-mail from some guy who is working on this:

https://github.com/Q-Con/pioq3/

and he was expressing interest in porting it so we could use it in RetroArch. I replied to him but I haven't heard back from him yet so I'm not sure if he will proceed with it.

I'd very much like to see a Quake 2 and 3 port to libretro GL. Sucks that we don't have any decent modern GL ports for Quake 2, and that  there is not a source port out there with a software renderer that has working colored lighting and all the other niceties of the hardware renderer, otherwise we could have gone that route.

**Comment by leilei-** [comment]
>and that there is not a source port out there with a software renderer that has working colored lighting 
*[cough](https://github.com/leilei-/Engoo)*. I backported the lighting to Q2's ref_soft at one point (and [qbism improved on it](https://github.com/qbism/Quake2-colored-refsoft) iirc) but couldn't get the model colored lighting to work as well.

**Comment by twinaphex** [comment]
Anything that could compile out of the box on Linux?

**Comment by leilei-** [comment]
Nothing that I know of.  Someone did try porting Engoo to linux once, but that someone was a bigoted dick. :/

I do have a libretro tyrquake compiling setup on here and I've thought about taking the lighting into it.  Shouldn't be that much of a compromise since you're not using the assembly routines anyhow

**Comment by leilei-** [comment]
[poke](https://github.com/leilei-/tyrquake/commit/6936212bf106c6a2a24210cfc92a8abc987056cf)

**Comment by twinaphex** [comment]
We now have a separate core for this -

https://github.com/libretro/vitaquake3
