### ISSUE TITLE
Wii U - TyrQuake "no items" issue

### ISSUE THREAD

**Issue by cucholix** [libretro/tyrquake#35]
It should load either pak0.pak or pak1.pak, but every time you try load them it says "no items".

There's no crash, black screen, or code dump, you can navigate normally after that. While I'm not sure when exactly the problem start to appear I would guess it was before 1.3.6 stable.

---------
To narrow the problem down...
I have 2 working binary copies of Tyrquake, but I'm not sure what date they are from.

The cores are:
1.3.6 - TyrQuake v0.62, according the file it was modified las time november 23 ‏‎7:24:24 it's working on my end. http://gbatemp.net/threads/retroarch-wiiu-wip.447670/page-165#post-7044143 <-the file

1.3.6 - TyrQuake v0.62, according the file it was modified las time december 3rd ‏‎ ‏‎19:00:40 it's working on my end. http://gbatemp.net/threads/retroarch-wiiu-wip.447670/page-163#post-7040531 <-the file

**Comment by ShadowOne333** [comment]
I can also confirm this issue.
It's something similar to what happens when you try to open a ROM in a core which requires a bios, you try to open the ROM, quick black screen and jumps back to the main menu with "No items" being listed.

My pak files are working fine on Quake for the Wii and in previous versions of TyrQuake pre-1.4.0.
I am unsure what commit broke it though between 1.3.6 and 1.4.0..
